function formatPRComment(analysis, prData) {
  const score = analysis.healthScore ?? 0;

  const healthEmoji = score >= 80 ? "🟢" : score >= 50 ? "🟡" : "🔴";

  const severityBadge = {
    error: "🔴 **ERROR**",
    warning: "🟠 **WARNING**",
    info: "🔵 **INFO**",
  };

  return `
## 🤖 **MergeMind PR Analysis**

> _Automated AI-powered pull request review_

---

### 🩺 **Overall Health**
${healthEmoji} **Score:** **${score}/100**

---

### 📝 **Summary**
${analysis.summary || "_No summary provided._"}

---

### 📊 **PR Statistics**

| Metric | Value |
|------|------|
| 📁 Files Changed | ${prData.changedFiles} |
| ➕ Lines Added | ${prData.additions} |
| ➖ Lines Deleted | ${prData.deletions} |
| 🔀 Commits | ${prData.commits} |

---

<details>
<summary><strong>🔍 Key Findings</strong></summary>

<br/>

${
  analysis.keyFindings?.length
    ? analysis.keyFindings.map((k) => `- ${k}`).join("\n")
    : "- ✅ No major issues detected"
}

</details>

---

<details>
<summary><strong>🛠 Suggestions & Improvements</strong></summary>

<br/>

${
  analysis.suggestions?.length
    ? analysis.suggestions
        .map(
          (s, i) => `
### ${severityBadge[s.severity] || "ℹ️ **INFO**"} — Issue ${i + 1}

- **📄 File:** \`${s.file || "N/A"}\`
- **❗ Issue:** ${s.description}
- **💡 Suggested Fix:**
\`\`\`
${s.suggestedFix}
\`\`\`
`
        )
        .join("\n")
    : "✅ **No suggestions — PR looks solid!**"
}

</details>

---

### 🧠 **MergeMind AI Verdict**
${
  score >= 80
    ? "✅ This PR is **healthy** and follows best practices."
    : score >= 50
    ? "⚠️ This PR is **acceptable**, but improvements are recommended."
    : "❌ This PR needs **attention before merging**."
}

<sub>🧠 Generated by <strong>MergeMind AI</strong> · Continuous PR Intelligence</sub>
`;
}

module.exports = {
  formatPRComment,
};
